### ISSUE TITLE
SemanticSearch notebooks: max text length not accurate

### ISSUE THREAD

**Issue by rnckp** [RedisAI/vecsim-demo#16]
Thanks for the tutorial!

Two remarks regarding `MAX_TEXT_LENGTH` for embeddings:
- The maximum sequence length of models is not measured in characters but in tokens. If you cut with `return val[:MAX_TEXT_LENGTH]` you encode less text than you actually can with your model.
- You do not need the `auto_truncate` function because sentence-transformer's `encode()` will do this automatically for you.

**Comment by GuyAv46** [comment]
Thanks for the suggestion! We'll look into it.
