### ISSUE TITLE
TypeError: search() got an unexpected keyword argument 'query_params'

### ISSUE THREAD

**Issue by mladen-korunoski** [RedisAI/vecsim-demo#4]
Hey,

I've used your notebook as guidance for my use case. I've loaded and indexed the data, which works fine. However, when I run a query I get the error above. Here is the code for executing the query:

```
query_emb = query_emb.astype(np.float32).tobytes()
q = redisearch.Query(f'@embedding:[$query_emb TOPK 5] => {{$EFRUNTIME : {EF}}}').sort_by('embedding_score').paging(0, 5).return_fields('embedding_score')
results = index.search(q, query_params={'query_emb': query_emb})
```

The problem is in the last line, meaning, the argument query_params is non-existent. This is also confirmed by the documentation:

```
Help on method search in module redisearch.client:

search(query) method of redisearch.client.Client instance
    Search the index for a given query, and return a result of documents
    
    ### Parameters
    
    - **query**: the search query. Either a text for simple queries with default parameters, or a Query object for complex queries.
                 See RediSearch's documentation on query format

```

I've used the `redislabs/redisearch:feature-vecsim` docker image.

Any help is appreciated.

**Comment by aaaaahaaaaa** [comment]
Facing the same issue here. @esandoval30 any clues by any chance?

**Comment by DvirDukhan** [comment]
@mladen-korunoski @aaaaahaaaaa 
please use `pip install git+https://github.com/RediSearch/redisearch-py.git@params`

**Comment by esandoval30** [comment]
@mladen-korunoski  @aaaaahaaaaa Please see updated demos with redis-py (which now supports RediSearch 2.4)
