### ISSUE TITLE
[Question] Can we search using existing redisai tensors?

### ISSUE THREAD

**Issue by manugarri** [RedisAI/vecsim-demo#6]
I already have millions of tensors on my redis instance (stored via redisAI tensorset).

I was hoping to be able to search similar items directly, instead of following this [notebook](https://github.com/RedisAI/vecsim-demo/blob/master/VisualSearch100k.ipynb) in which basically redisai is not used (just redissearch with byte serialized embeddings).

**Comment by esandoval30** [comment]
Hi @manugarri. Unfortunately, there is currently no way to apply our vector indexing techniques to RedisAI Tensors.

I'd like to discuss your use case to understand what options we could build in the future.

Feel free to email me ed . sandoval @ redis.com

@DvirDukhan @K-Jo FYI

**Comment by manugarri** [comment]
@esandoval30 sent u an email :)
